import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { api } from "../utils/api";

const CommunityPage: NextPage = () => {
  const icons = api.icons.getCommunityIcons.useQuery();

  return (
    <>
      <Head>
        <title>Community Icons</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-start">
        <h1 className="my-12 text-4xl">Community Icons</h1>
        <ul className="grid grid-cols-3 gap-6 sm:grid-cols-4 md:grid-cols-6">
          {icons.data?.map((icon) => (
            <li key={icon.id}>
              <Image
                width="100"
                height="100"
                alt={icon.prompt ?? "Image of the icon"}
                src={`https://dalle-icon-generator.s3.amazonaws.com/${icon.id}`}
                className="w-full rounded-md"
              />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default CommunityPage;

//TODO:
// Get all the icons user has generated
// Create another tRPC endpoint: Go to server/api/routers/, create icons.ts
// Go to server/api/root.ts, add 'icons: iconsRouter'
// Now we can access the router at frontend
