import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import PrimaryLinkButton from "../components/PrimaryLinkButton";

function HeroBanner() {
  return (
    <section className="mt-12 grid max-w-6xl grid-cols-1 place-items-start gap-12 px-12 sm:grid-cols-2">
      <div className="flex flex-col gap-2">
        <h1 className="text-4xl">Generate icons with a click of a button</h1>
        <p className="mb-8 text-lg font-thin">
          Use AI to generate icons in seconds instead of paying a designer and
          waiting for them to create them for you.
        </p>
        <div className="mt-4 w-full">
          <PrimaryLinkButton href="/generate">Get Started</PrimaryLinkButton>
        </div>
      </div>

      <div className="order-first sm:order-none">
        <Image
          src="/media/landing-banner.png"
          alt="banner image"
          width="400"
          height="300"
        />
      </div>
    </section>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dalle Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-start ">
        <HeroBanner />
        <div className="mt-24 px-12 text-left xl:px-36">
          <h1 className="text-4xl leading-10">
            I am delighted to offer newly registered users 10 credits that can
            be used to generate your very own stunning icons.
          </h1>
        </div>
      </main>
    </>
  );
};

export default Home;
